from pathlib import Path

ABSOLUTE_PATH = Path(r"C:\Users\Tomas\Desktop\Thesis Stuff\Survival_Analysis_Thesis\Coding")
PATH_TO_DATA_FOLDER = ABSOLUTE_PATH / "Data"
PATH_TO_RAW_DATA  = PATH_TO_DATA_FOLDER / "raw"
PATH_TO_INTERIM_DATA =  PATH_TO_DATA_FOLDER / "interim"
PATH_TO_FINAL_DATA = PATH_TO_DATA_FOLDER / "final"

PATH_TO_RAW_ACTIVITY_DATA = PATH_TO_RAW_DATA / "activity.csv"
PATH_TO_RAW_USER_DATA = PATH_TO_RAW_DATA / "user.csv"
PATH_TO_RAW_VEHICLE_DATA = PATH_TO_RAW_DATA / "vehicle.csv"

PATH_TO_RAW_ACTIVITY_DATA_1000 = PATH_TO_RAW_DATA / "activity_1000.csv"
PATH_TO_RAW_USER_DATA_1000 = PATH_TO_RAW_DATA / "user_1000.csv"
PATH_TO_RAW_VEHICLE_DATA_1000 = PATH_TO_RAW_DATA / "vehicle_1000.csv"

